SimpleShopMVC/Models/CartItem.cs
namespace SimpleShopMVC.Models;

public class CartItem
{
    public int Id { get; set; }
    public int Quantity { get; set; }
    public Product Product { get; set; }
}

SimpleShopMVC/Models/ErrorViewModel.cs
namespace SimpleShopMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SimpleShopMVC/Models/Product.cs
namespace SimpleShopMVC.Models;

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
    public string Description { get; set; }
    public string ImageUrl { get; set; }
}

SimpleShopMVC/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleShopMVC.Models;
using SimpleShopMVC.Data;

public class CartController : Controller
{
    private readonly ApplicationDbContext _context = new();

    public async Task<IActionResult> Index()
    {
        List<CartItem> cartItems = await _context.CartItems.Include(x => x.Product).ToListAsync();
        return View(cartItems);
    }
    
    public IActionResult AddToCart(int id)
    {
        Product product = _context.Products.Find(id);
        if (product == null)
        {
            return NotFound();
        }

        CartItem cartItem = new CartItem
        {
            Product = product,
            Quantity = 1
        };
        
        CartItem existingCartItem = _context.CartItems.FirstOrDefault(ci => ci.Product.Id == id);
        if (existingCartItem != null)
        {
            existingCartItem.Quantity++;
            _context.Update(existingCartItem);
        }
        else
        {
            _context.CartItems.Add(cartItem);
        }
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
    
    public IActionResult RemoveFromCart(int id)
    {
        CartItem cartItem = _context.CartItems.Find(id);
        if (cartItem == null)
        {
            return NotFound();
        }

        _context.CartItems.Remove(cartItem);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
}

SimpleShopMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SimpleShopMVC.Models;

namespace SimpleShopMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SimpleShopMVC/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleShopMVC.Models;
using SimpleShopMVC.Data;

public class ProductsController : Controller
{
    private readonly ApplicationDbContext _context;
    
    public ProductsController()
    {
        _context = new ApplicationDbContext();
    }
    
    public async Task<IActionResult> Index()
    {
        List<Product> products = await _context.Products.ToListAsync();
        return View(products);
    }
    
    public async Task<IActionResult> Create()
    {
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Price,Description,ImageUrl")] Product product)
    {
        if (ModelState.IsValid)
        {
            _context.Add(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        else
        {
            Console.WriteLine("Not Valid");
            Console.WriteLine(ModelState.ValidationState);
            return View(product);
        }
        return RedirectToAction(nameof(Index));
    }
    
    public async Task<IActionResult> Remove(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        
        var product = await _context.Products.FirstOrDefaultAsync(m => m.Id == id);
        if (product == null)
        {
            return NotFound();
        }
        // Remove the product from the context
        _context.Products.Remove(product);
        // Save the changes
        await _context.SaveChangesAsync();
        
        return RedirectToAction(nameof(Index));
    }
}

SimpleShopMVC/Views/Cart/Index.cshtml
@model List<CartItem>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Cart list</h2>

<!-- Render list of cart items with remove action -->

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="@item.Product.ImageUrl" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title
                    ">@item.Product.Name</h5>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a asp-action="RemoveFromCart" asp-controller="Cart" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Remove from Cart</a>
                        </div>
                        <small class="text-muted
                                            ">USD  @string.Format("{0:C}", @item.Product.Price)</small>
                        <small class="text-muted
                    ">QTY: @item.Quantity</small>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

SimpleShopMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SimpleShopMVC/Views/Products/Create.cshtml
@model Product
@{
    ViewData["Title"] = "Product create";
}

<div class="text-center">
    <h1 class="display-4">Product create</h1>
    
    <form method="post" asp-action="Create">
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
    <!-- description -->
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <!-- ImageUrl -->
    <div class="form-group">
        <label asp-for="ImageUrl"></label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    </form>
    
</div>

SimpleShopMVC/Views/Products/Index.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Products List";
}

<div class="text-center">
    <h1 class="display-4">Products list</h1>
    
    <!-- Products list with images, prices and add to cart btn with qty -->
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="@product.ImageUrl" alt="Card image cap">
                    <!-- Delete button -->
                    <a asp-action="Remove" asp-controller="Products" asp-route-id="@product.Id" class="btn btn-danger">Delete</a>
                    <div class="card-body">
                        <h5 class="card-title
                        ">@product.Name</h5>
                        <p class="card-text">@product.Description</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@product.Id" class="btn btn-sm btn-outline-secondary">Add to Cart</a>
                            </div>
                            <small class="text-muted
                            ">USD  @string.Format("{0:C}", @product.Price)</small>
                            
                        </div>
                    </div>
                </div>
            </div>
}
</div>
        <!-- Create product button -->
    <a class="btn btn-primary" asp-action="Create" asp-controller="Products">Create product</a>
</div>

SimpleShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SimpleShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SimpleShopMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleShopMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - SimpleShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>